name: Build Mac App

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Get files
      uses: actions/checkout@v3

    - name: Install Python
      run: brew install python3

    - name: Install PyInstaller
      run: pip3 install pyinstaller

    - name: Build Mac App
      run: |
        pyinstaller --windowed --name "KidzibooksInventory" part2.py
        ls dist

    - name: Upload Built App
      uses: actions/upload-artifact@v3
      with:
        name: KidzibooksInventory-Mac
        path: dist/*
